import {
  ShoppingBasket,
  Utensils,
  Sandwich,
  Cookie,
  CupSoda,
  Bike,
  Fuel,
  Bus,
  CarTaxiFront,
  Car,
  MapPin,
  Zap,
  Droplet,
  Wifi,
  Phone,
  Signal,
  Tv,
  Home,
  Trash2,
  Receipt,
  Users,
  Baby,
  HeartHandshake,
  Gift,
  Shirt,
  Sparkles,
  Smile,
  Smartphone,
  ShoppingBag,
  Clapperboard,
  Gamepad2,
  PartyPopper,
  MonitorPlay,
  UsersRound,
  GraduationCap,
  BookOpen,
  Laptop,
  Presentation,
  Pill,
  Stethoscope,
  Cross,
  Church,
  MoonStar,
  HandHeart,
  CreditCard,
  PiggyBank,
  TrendingUp,
  Ellipsis,
  Briefcase,
  Store,
  Wallet,
  RotateCcw,
  Circle,
  type LucideIcon,
} from "lucide-react"
import { cn } from "@/lib/utils"

const ICONS: Record<string, LucideIcon> = {
  "shopping-basket": ShoppingBasket,
  utensils: Utensils,
  sandwich: Sandwich,
  cookie: Cookie,
  "cup-soda": CupSoda,
  bike: Bike,
  fuel: Fuel,
  bus: Bus,
  "car-taxi-front": CarTaxiFront,
  car: Car,
  "map-pin": MapPin,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  phone: Phone,
  signal: Signal,
  tv: Tv,
  home: Home,
  "trash-2": Trash2,
  receipt: Receipt,
  users: Users,
  baby: Baby,
  "heart-handshake": HeartHandshake,
  gift: Gift,
  shirt: Shirt,
  sparkles: Sparkles,
  smile: Smile,
  smartphone: Smartphone,
  "shopping-bag": ShoppingBag,
  clapperboard: Clapperboard,
  "gamepad-2": Gamepad2,
  "party-popper": PartyPopper,
  "monitor-play": MonitorPlay,
  "users-round": UsersRound,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  laptop: Laptop,
  presentation: Presentation,
  pill: Pill,
  stethoscope: Stethoscope,
  cross: Cross,
  church: Church,
  "moon-star": MoonStar,
  "hand-heart": HandHeart,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  ellipsis: Ellipsis,
  briefcase: Briefcase,
  store: Store,
  wallet: Wallet,
  "rotate-ccw": RotateCcw,
}

export function CategoryIcon({
  icon,
  className,
  containerClassName,
}: {
  icon: string
  className?: string
  containerClassName?: string
}) {
  const Icon = ICONS[icon] ?? Circle

  return (
    <span
      className={cn(
        "flex size-9 shrink-0 items-center justify-center rounded-full bg-accent text-accent-foreground",
        containerClassName
      )}
    >
      <Icon className={cn("size-4.5", className)} strokeWidth={2} />
    </span>
  )
}
